@startuml Diagrama_Sequencia_3

title Atualizar Agendamento

actor foo1 as "Usuário"
boundary foo2 as "Interface de Agendamento"
control foo3 as "Gerenciador de Agendamentos"
entity foo4 as "Agendamento"

foo1 -> foo2 : Solicitar atualização de agendamento
foo2 -> foo3 : Obter agendamento por id

alt Se agendamento encontrado

    foo3 -> foo4 : Atualizar agendamento
    foo4 -> foo3 : Salvar agendamento atualizado
    foo3 -> foo2 : Atualizar lista de agendamentos
    foo2 -> foo1 : Exibir mensagem de sucesso

else Se agendamento não encontrado

    foo3 -> foo2 : Exibir erro
    foo2 -> foo1 : Exibir mensagem de erro

end
@enduml
