@startuml Diagrama_Classe_4
title Diagrama de Classe 4 - Visão

package visao {
  class Visao<T> {
    -objetos: List<T>
    +exibir(id: int): String
    +listar(): String
    +atualizar(id: int): String
    +excluir(id: int): String
  }
}
@enduml
