@startuml Gerenciamento_Calendario_Cuidados
title Gerenciamento de Calendário de Cuidados

left to right direction

actor Usuario as u

usecase "Adicionar uma nova planta" as UC1
usecase "Listar todas as plantas" as UC2
usecase "Obter detalhes de uma planta específica" as UC3
usecase "Atualizar informações de uma planta" as UC4
usecase "Remover uma planta" as UC5

u --> UC1
u --> UC2
u --> UC3
u --> UC4
u --> UC5

@enduml
