@startuml Diagrama_Classe_2
title Front-End Diagrama de Classe 2 - Utilitários

package utils {
  abstract class FabricaDePlanta {
    +fabricarPlanta(nome: String, dataAquisicao: DateTime, tipoPlanta: TipoPlanta, agendamentos: List<Agendamento>)
  }

  enum TipoPlanta {
    briofita
    pteridofita
    gimnosperma
    angiosperma
  }

  enum Evento {
    regamento
    podamento
    adubacao
    trocaVaso
  }

  interface Iterador<T> {
    temProximo(): bool
    proximo(): T
    atual(): T
  }

  class PlantaIterador {
    -plantas: List<Plantas>
    -indiceAtual: int
    PlantaIterador(plantas: List<Plantas>)
  }

  class AgendamentoIterador {
    -agendamentos: List<Agendamento>
    -indiceAtual: int
    AgendamentoIterador(agendamentos: List<Agendamento>)
  }

  interface Agregador<T> {
    +geraIterador(): T
  }

  class Plantas {
    -plantas: List<Plantas>
    -indiceAtual: int
    -plantaIterador: PlantaIterador
  }

  class Agendamentos {
    -agendamentos: List<Plantas>
    -indiceAtual: int
    -agendamentosIterador: AgendamentoIterador
  }

  Iterador <|.. PlantaIterador
  Iterador <|.. AgendamentoIterador

  Agregador <|.. Plantas
  Agregador <|.. Agendamentos
}
@enduml
