@startuml Diagrama_Classe_4
title Front-End Diagrama de Classe 4 - Visão

package visao {
  class Visao<T> {
    -agregador: Agregador
    +exibir(id: int): void
    +listar(): void
    +atualizar(id: int): void
    +excluir(id: int): void
  }
}
@enduml
