@startuml Diagrama_Classe_2
title Front-End Diagrama de Classe 2 - Utilitários

package utils {
  abstract class FabricaDePlanta {
    +fabricarPlanta(nome: String, dataAquisicao: DateTime, tipoPlanta: TipoPlanta, agendamentos: List<Agendamento>)
  }

  enum TipoPlanta {
    briofita
    pteridofita
    gimnosperma
    angiosperma
  }

  interface Iterador<T> {
    temProximo(): bool
    proximo(): T
    atual(): T
  }

  class PlantaIterador {
    -plantas: List<Plantas>
    
    PlantaIterador(plantas: List<Plantas>)
  }

  class AgendamentoIterador {
    -agendamentos: List<Agendamento>
    
    AgendamentoIterador(agendamentos: List<Agendamento>)
  }

  Iterador <|.. PlantaIterador
  Iterador <|.. AgendamentoIterador
}
@enduml
