@startuml Diagrama_Sequencia_Planta_1

title Visualizar Planta

actor foo1 as "Usuário"
boundary foo2 as "Interface de Planta"
control foo3 as "Gerenciador de Plantas"
entity foo4 as "Planta"

foo1 -> foo2 : Solicitar visualização de planta
foo2 -> foo3 : Obter planta por id

alt Se planta encontrada

    foo3 -> foo4 : Buscar planta
    foo4 -> foo3 : Retornar dados da planta
    foo3 -> foo2 : Exibir planta
    foo2 -> foo1 : Exibir detalhes da planta

else Se planta não encontrada

    foo3 -> foo2 : Exibir erro
    foo2 -> foo1 : Exibir mensagem de erro

end
@enduml
